#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ -n "${DIB_CREATE_USERNAME}" ]]; then
    useradd --shell /bin/bash --groups sudo --create-home "${DIB_CREATE_USERNAME}"

    if [[ -n "${DIB_ADD_AUTHORIZED_SSH_KEY}" ]]; then
        mkdir -m700 "/home/${DIB_CREATE_USERNAME}/.ssh"
        echo "${DIB_ADD_AUTHORIZED_SSH_KEY}" > "/home/${DIB_CREATE_USERNAME}/.ssh/authorized_keys"
    fi
fi
