#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

systemctl enable systemd-networkd
cat << EOF > /etc/systemd/networkd/eth0.network
[Match]
Name=eth0

[Network]
DHCP=yes
EOF
